POST http://localhost:3000/chamados
Content-Type: application/json

{
"descChamado": "O volume da caixa de som não abaixa",
// dataAberturaChamado DateTime  @default(now())
"idUsuario":2,
"idCategoria": 1
}

###

GET http://localhost:3000/chamados/1


###


GET http://localhost:3000/usuarios/10


###

DELETE http://localhost:3000/chamados/3


###

DELETE http://localhost:3000/usuarios/3