POST http://localhost:3000/chamados
Content-Type: application/json

{
"descChamado": "O computador está muito lento",
// dataAberturaChamado DateTime  @default(now())
"idUsuario": 4,
"idCategoria": 2,
"idAndamento": 1
}