
POST http://localhost:3000/chamados
Content-Type: application/json

{
        "nomeChamado": "Computador lento",
        "descChamado": "O computador ficou bem mais lento de 1 mês para cá. Tudo demora muito",
        "idUsuario": 2,
        "idLab": 105,
        "idComputador": 3,
        "idCategoria": 2
}


###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
"nomeUsuario": "Felipe",
"emailUsuario": "felipe@ig.com",
"telefoneUsuario": "11993354444"
}


###


PATCH http://localhost:3000/usuarios/2
Content-Type: application/json

{
"nomeUsuario": "Luiz"
}



###


GET http://localhost:3000/chamados/1


###


GET http://localhost:3000/usuarios/2


###


PATCH http://localhost:3000/usuarios/2
Content-Type: application/json

{
"emailUsuario": "luiz@gmail.com.br"
}



###

DELETE http://localhost:3000/chamados/3


###


DELETE http://localhost:3000/usuarios/3


###


# inclusão do idSuporte, ou seja, do técnico responsável, ao chamado, quando ele assumir a tarefa.
PATCH http://localhost:3000/chamados/2
Content-Type: application/json

{
"idSuporte": 1
}


###



